from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.web_viewer = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.web_viewer.setGeometry(QtCore.QRect(0, 0, 671, 441))
        self.web_viewer.setUrl(QtCore.QUrl("about:blank"))
        self.web_viewer.setObjectName("web_viewer")
        self.get_x1 = QtWidgets.QLineEdit(self.centralwidget)
        self.get_x1.setGeometry(QtCore.QRect(690, 90, 113, 32))
        self.get_x1.setObjectName("get_x1")
        self.get_y1 = QtWidgets.QLineEdit(self.centralwidget)
        self.get_y1.setGeometry(QtCore.QRect(690, 130, 113, 32))
        self.get_y1.setObjectName("get_y1")
        self.get_x2 = QtWidgets.QLineEdit(self.centralwidget)
        self.get_x2.setGeometry(QtCore.QRect(690, 170, 113, 32))
        self.get_x2.setObjectName("get_x2")
        self.get_y2 = QtWidgets.QLineEdit(self.centralwidget)
        self.get_y2.setGeometry(QtCore.QRect(690, 210, 113, 32))
        self.get_y2.setObjectName("get_y2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 97, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 138, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(810, 177, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(810, 217, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_log.setGeometry(QtCore.QRect(0, 440, 1021, 192))
        self.txt_log.append("لطفا مقادیر خواسته شده را وارد کنید و سپس بر روی دکمه محاسبه کن کلیک کنید.")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_log.setFont(font)
        self.txt_log.setObjectName("txt_log")
        self.btn_clean = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clean.setGeometry(QtCore.QRect(690, 260, 150, 34))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_clean.setFont(font)
        self.btn_clean.setObjectName("btn_clean")
        self.btm_run = QtWidgets.QPushButton(self.centralwidget)
        self.btm_run.setGeometry(QtCore.QRect(860, 260, 151, 34))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btm_run.setFont(font)
        self.btm_run.setObjectName("btm_run")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(690, 300, 321, 34))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1020, 617))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../background image/back2.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.txt_log.raise_()
        self.get_x1.raise_()
        self.get_y1.raise_()
        self.get_x2.raise_()
        self.get_y2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.web_viewer.raise_()
        self.btn_clean.raise_()
        self.btm_run.raise_()
        self.btn_exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btm_run.clicked.connect(self.run)
        self.btn_clean.clicked.connect(self.clean)
        self.btn_exit.clicked.connect(self.exit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def run(self):
        self.txt_log.clear()
        self.txt_log.append("در حال رسم مختصصات لطفا شکیبا باشید.")
        X1 = int(self.get_x1.text())
        X2 = int(self.get_x2.text())
        Y1 = int(self.get_y1.text())
        Y2 = int(self.get_y2.text())

        from bresenham_algo import bresenham as br
        br(X1,X2,Y1,Y2)
        self.txt_log.clear()
        self.txt_log.append("مختصصات با موفقیت رسم شد.\n")
        self.txt_log.append("همچنین فایلی با نام Bresenham lines.html در مسیر جاری ایجاد شد.")
        import os
        self.web_viewer.load(QtCore.QUrl.fromLocalFile(os.path.abspath('Bresenham lines.html')))
        
    def clean(self):
        self.get_x1.clear()
        self.get_x2.clear()
        self.get_y1.clear()
        self.get_y2.clear()
        self.txt_log.clear()
        self.txt_log.append("لطفا مقادیر خواسته شده را وارد کنید و سپس بر روی دکمه محاسبه کن کلیک کنید.")
        self.web_viewer.back()
    
    def exit(self):
        MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "لطفا مقدار X1 را وارد کنید"))
        self.label_2.setText(_translate("MainWindow", "لطفا مقدار Y1 را وارد کنید"))
        self.label_3.setText(_translate("MainWindow", "لطفا مقدار X2 را وارد کنید"))
        self.label_4.setText(_translate("MainWindow", "لطفا مقدار Y2 را وارد کنید"))
        self.btn_clean.setText(_translate("MainWindow", "پاک کن"))
        self.btm_run.setText(_translate("MainWindow", "محاسبه کن"))
        self.btn_exit.setText(_translate("MainWindow", "خروج"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
